apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: fbarbera
      protocol: layer2
      addresses:
      - 192.168.99.101-192.168.99.101