apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
  annotations:
    metallb.universe.tf/allow-shared-ip: fbarbera
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306